### ISSUE TITLE
No image displayed in Free Champion Rotation page

### ISSUE THREAD

**Issue by myyeowoo** [IrtizaDelwar/RiftAnalytics#10]
No image is displayed when you click 15th champion.

**Comment by IrtizaDelwar** [comment]
I assume this has to do with tahm kench and not the "15th"

So right now I hard code a link by adding the champion name after a certain url. It could be that the url is different for this specific champion. So we should pull the splash url from the api instead of hard coding a url in. Ill work on that in a bit.

**Comment by IrtizaDelwar** [comment]
Actual problem was space in image url for champions with a space in it. Fixed.
